In [ ]:
Q. 6 6 을 입력해주면 6 X 6 매트릭스에 나선형 회전을 한 값을 출력해야한다.

6 6

 0   1   2   3   4   5
 19  20  21  22  23   6
 18  31  32  33  24   7
 17  30  35  34  25   8
 16  29  28  27  26   9
 15  14  13  12  11  10

In [3]:
 # 넘파이 라이브러리를 불러올 때는 import 부터 진행을 합니다.

import numpy as np # <- np.array() 함수 만들 수 있음.

In [14]:
# Z =np.arange(0,35+1) # arrange 로 range 수를 넣어서 ndarray를 만들면 1차원으로 생성할 수 있다.
# print(Z)

In [15]:
# Z = Z.reshape((6,6)) # shape 으로 6행 6열로 재배열
# print(Z)

In [20]:
# arr=np.arange(32).reshape((8,4))
# print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [21]:
# print(arr[[1,5,6,2]]) #1인덱스 : 2번째 행 / 5인덱스 : 6번째 행 / 7인덱스 8번째행 이해 X

[[ 4  5  6  7]
 [20 21 22 23]
 [24 25 26 27]
 [ 8  9 10 11]]


In [22]:
# print( arr[[-1,-5,-7,-2]])

[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]


In [24]:
arr6=np.array([0,1,2,3,4,5],[19,20,21,22,23,24,25,26,6],[18,31,32,33,24,7],[17,30,35,34,25,8],[16,29,28,27,26,9],[15,14,13,12,11,10])
print(arr6)

TypeError: array() takes from 1 to 2 positional arguments but 6 were given

In [31]:
B = np.array([(0,1,2,3,4,5),(19,20,21,22,23,24,25,26,6),(18,31,32,33,24,7),(17,30,35,34,25,8),(16,29,28,27,26,9),(15,14,13,12,11,10)])
print(B)

[(0, 1, 2, 3, 4, 5) (19, 20, 21, 22, 23, 24, 25, 26, 6)
 (18, 31, 32, 33, 24, 7) (17, 30, 35, 34, 25, 8) (16, 29, 28, 27, 26, 9)
 (15, 14, 13, 12, 11, 10)]


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [32]:
BA = np.array([(0,1,2,3,4,5),(19,20,21,22,23,24,25,26,6),(18,31,32,33,24,7),(17,30,35,34,25,8),(16,29,28,27,26,9),(15,14,13,12,11,10)])
print(HANG)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.
